program Caixa;
uses
  Forms,
  UNF_Funcoes in 'UNF_Funcoes.pas',
  UNF_Bematech in 'UNF_Bematech.pas',
  UNF_Frente in 'UNF_Frente.pas' {FRM_Frente},
  UNF_Fundo in 'UNF_Fundo.pas' {FRM_Fundo},
  UNF_Fecha in 'UNF_Fecha.pas' {FRM_Fecha},
  UNF_Mesa in 'UNF_Mesa.pas' {FRM_Mesa},
  UNF_Pergunta in 'UNF_Pergunta.pas' {FRM_Pergunta},
  UNF_Mensagem in 'UNF_Mensagem.pas' {FRM_Mensagem},
  UNF_MensagemDeErro in 'UNF_MensagemDeErro.pas' {FRM_MensagemDeErro},
  UNF_Manutencao in 'UNF_Manutencao.pas' {FRM_Manutencao},
  UNF_Login in 'UNF_Login.pas' {FRM_Login},
  UNF_Menu in 'UNF_Menu.pas' {FRM_Menu},
  UNF_Desconto in 'UNF_Desconto.pas' {FRM_Desconto},
  UNF_Senha in 'UNF_Senha.pas' {FRM_Senha},
  UNF_VerFicha in 'UNF_VerFicha.pas' {FRM_VerFicha},
  UNF_MapaMesa in 'UNF_MapaMesa.pas' {FRM_MapaMesa},
  UNF_FiltroFecha in 'UNF_FiltroFecha.pas' {FRM_FiltroFecha},
  UNQ_Fecha in 'UNQ_Fecha.pas' {QRP_Fecha: TQuickRep},
  UNF_Entrada in 'UNF_Entrada.pas' {FRM_Entrada},
  UNF_FechaDia in 'UNF_FechaDia.pas' {FRM_FechaDia},
  UNF_Modulo in 'UNF_Modulo.pas' {FRM_Modulo: TDataModule},
  UNF_Calendario in 'UNF_Calendario.pas' {FRM_Calendario},
  UNF_FilRelatorios in '..\Retaguarda\UNF_FilRelatorios.pas' {FRM_FilRelatorios},
  UNQ_RGTotais in '..\Retaguarda\UNQ_RGTotais.pas' {QRP_RGTotais: TQuickRep},
  UNQ_Rodape in '..\Retaguarda\UNQ_Rodape.pas' {QRP_Rodape: TQuickRep},
  UNQ_Titulo in '..\Retaguarda\UNQ_Titulo.pas' {QRP_Titulo: TQuickRep},
  UNQ_RGCaixa in '..\Retaguarda\UNQ_RGCaixa.pas' {QRP_RGCaixa: TQuickRep},
  UNQ_RGCancelados in '..\Retaguarda\UNQ_RGCancelados.pas' {QRP_RGCancelados: TQuickRep},
  UNQ_RGFormaPagto in '..\Retaguarda\UNQ_RGFormaPagto.pas' {QRP_RGFormaPagto: TQuickRep},
  UNQ_RGFunCancelados in '..\Retaguarda\UNQ_RGFunCancelados.pas' {QRP_RGFunCancelados: TQuickRep},
  UNQ_RGGrupo in '..\Retaguarda\UNQ_RGGrupo.pas' {QRP_RGGrupo: TQuickRep},
  UNQ_RGHora in '..\Retaguarda\UNQ_RGHora.pas' {QRP_RGHora: TQuickRep},
  UNQ_RGProduto in '..\Retaguarda\UNQ_RGProduto.pas' {QRP_RGProduto: TQuickRep},
  UNQ_RGQuilo in '..\Retaguarda\UNQ_RGQuilo.pas' {QRP_RGQuilo: TQuickRep},
  UNF_FilFechaCaixa1 in '..\Retaguarda\UNF_FilFechaCaixa1.pas' {FRM_FilFechaCaixa1},
  UNQ_FecCaixaDetalhado in '..\Retaguarda\UNQ_FecCaixaDetalhado.pas' {QRP_FecCaixaDetalhado: TQuickRep},
  UNF_AtualizaBase in 'UNF_AtualizaBase.pas' {FRM_AtualizaBase},
  UNQ_RGMontana in '..\Retaguarda\UNQ_RGMontana.pas' {QRP_RGMontana: TQuickRep},
  UNF_FuncoesECF in 'UNF_FuncoesECF.pas',
  UNF_Daruma32 in 'UNF_Daruma32.pas',
  UNF_NewMensagem in 'UNF_NewMensagem.pas' {FRM_NewMensagem},
  UNF_Nota in 'UNF_Nota.pas' {FRM_Nota},
  UNF_FNCTermica in 'UNF_FNCTermica.pas',
  UNF_VariasFormas in 'UNF_VariasFormas.pas' {FRM_VariasFormas},
  UNF_AbastSangria in 'UNF_AbastSangria.pas' {FRM_AbastSangria},
  UNF_PesProduto in 'UNF_PesProduto.pas' {FRM_PesProduto},
  UNF_PesCliente in 'UNF_PesCliente.pas' {FRM_PesCliente},
  UNF_PesCondPagto in 'UNF_PesCondPagto.pas' {FRM_PesCondPagto},
  UNQ_FecCaixaDetalhadoNovo in 'UNQ_FecCaixaDetalhadoNovo.pas' {QRP_FecCaixaDetalhadoNovo: TQuickRep},
  UNF_LanItem in 'UNF_LanItem.pas' {FRM_LanItem},
  UNF_CancelaItem in 'UNF_CancelaItem.pas' {FRM_CancelaItem},
  UNF_Diarias in 'UNF_Diarias.pas' {FRM_Diarias},
  UNF_LanDiaria in 'UNF_LanDiaria.pas' {FRM_LanDiaria},
  UNF_FinalizaDiaria in 'UNF_FinalizaDiaria.pas' {FRM_FinalizaDiaria},
  UNF_ConfMBD in 'UNF_ConfMBD.pas' {FRM_ConfMBD},
  UNF_FilFechaCaixa1Novo in '..\Retaguarda\UNF_FilFechaCaixa1Novo.pas' {FRM_FilFechaCaixa1Novo},
  UNQ_RGFinanceiro in '..\Retaguarda\UNQ_RGFinanceiro.pas' {QRP_RGFinanceiro: TQuickRep},
  UNQ_RGFunCanceladosFC in '..\Retaguarda\UNQ_RGFunCanceladosFC.pas' {QRP_RGFunCanceladosFC: TQuickRep},
  UNQ_RGProdutoR in '..\Retaguarda\UNQ_RGProdutoR.pas' {QRP_RGProdutoR: TQuickRep},
  UNQ_RGSangriaAbast in '..\Retaguarda\UNQ_RGSangriaAbast.pas' {QRP_RGSangriaAbast: TQuickRep},
  UNQ_RGTroco in '..\Retaguarda\UNQ_RGTroco.pas' {QRP_RGTroco: TQuickRep},
  UNF_FilRelatoriosP in '..\Retaguarda\UNF_FilRelatoriosP.pas' {FRM_FilRelatoriosP},
  UNF_FilRelatoriosPe in '..\Retaguarda\UNF_FilRelatoriosPe.pas' {FRM_FilRelatoriosPe},
  UNF_FilRelatoriosPeO in '..\Retaguarda\UNF_FilRelatoriosPeO.pas' {FRM_FilRelatoriosPeO},
  UNF_FilRelatoriosM in '..\Retaguarda\UNF_FilRelatoriosM.pas' {FRM_FilRelatoriosM},
  UNF_FilRelatoriosMO in '..\Retaguarda\UNF_FilRelatoriosMO.pas' {FRM_FilRelatoriosMO},
  UNF_FilRelatoriosOD in '..\Retaguarda\UNF_FilRelatoriosOD.pas' {FRM_FilRelatoriosOD},
  UBQ_RGProducao in '..\Retaguarda\UBQ_RGProducao.pas' {QRP_RGProducao: TQuickRep},
  UNQ_RGMensalista in '..\Retaguarda\UNQ_RGMensalista.pas' {QRP_RGMensalista: TQuickRep},
  UNQ_RGFichasAbertas in '..\Retaguarda\UNQ_RGFichasAbertas.pas' {QRP_RGFichasAbertas: TQuickRep},
  UNQ_Assinatura in '..\Retaguarda\UNQ_Assinatura.pas' {QRP_Assinatura: TQuickRep},
  UNF_VerFicha2 in 'UNF_VerFicha2.pas' {FRM_VerFicha2},
  UNF_VerFichaF in 'UNF_VerFichaF.pas' {FRM_VerFichaF},
  UNF_LimpaSujMesa in 'UNF_LimpaSujMesa.pas' {FRM_LimpaSujMesa},
  UNF_Toledo in 'UNF_Toledo.pas',
  UNF_EntregaMa in 'UNF_EntregaMa.pas' {FRM_EntregaMa},
  UNF_EntreBaixa in 'UNF_EntreBaixa.pas' {FRM_EntreBaixa},
  UNF_ModeloSF in 'UNF_ModeloSF.pas' {FRM_ModeloSF},
  UNF_Cliente in 'UNF_Cliente.pas' {FRM_Cliente},
  UNQ_Cliente in '..\Retaguarda\UNQ_Cliente.pas' {QRP_Cliente: TQuickRep},
  UNF_ETQCliente in '..\Retaguarda\UNF_ETQCliente.pas' {FRM_ETQCliente},
  UNF_PesLookUp in '..\Retaguarda\UNF_PesLookUp.pas' {FRM_PesLoockUP},
  UNF_ETIQCliente in '..\Retaguarda\UNF_ETIQCliente.pas' {FRM_ETIQCliente},
  UNF_ETIQFicha in '..\Retaguarda\UNF_ETIQFicha.pas' {FRM_ETIQFicha},
  UNF_ETIQProduto in '..\Retaguarda\UNF_ETIQProduto.pas' {FRM_ETIQProduto},
  UNF_EtiFicha in '..\Retaguarda\UNF_EtiFicha.pas' {FRM_EtiFicha},
  UNF_EtiProduto in '..\Retaguarda\UNF_EtiProduto.pas' {FRM_EtiProduto},
  UNF_Tarifador in 'UNF_Tarifador.pas' {FRM_Tarifador},
  UNF_RGDiaria in '..\Retaguarda\UNF_RGDiaria.pas' {QRP_RGDiaria: TQuickRep},
  UNF_CupDiaria in 'UNF_CupDiaria.pas' {FRM_CupDiaria},
  UNF_DadosCupom in 'UNF_DadosCupom.pas' {FRM_DadosCupom},
  UNQ_ETIQProdutoGond in '..\Retaguarda\UNQ_ETIQProdutoGond.pas' {QRP_ETIQProdutoGond: TQuickRep},
  UNQ_DirCliente in '..\Retaguarda\UNQ_DirCliente.pas' {QRP_DirCliente: TQuickRep},
  UNF_DirCliente in '..\Retaguarda\UNF_DirCliente.pas' {FRM_DirCliente},
  UNF_Autorizacao in '..\Retaguarda\UNF_Autorizacao.pas' {FRM_Autorizacao},
  UNF_ExtratoComanda3 in 'UNF_ExtratoComanda3.pas' {QRP_ExtratoComanda3: TQuickRep},
  UNF_TransMesa in 'UNF_TransMesa.pas' {FRM_TransMesa},
  IBErros in '..\Retaguarda\IBErros.pas',
  UNF_AgruparItens in 'UNF_AgruparItens.pas' {FRM_AgruparItens},
  UNF_Entrega in 'UNF_Entrega.pas' {FRM_Entrega},
  UNF_TEF in 'UNF_TEF.pas',
  UNF_CliPendencia in 'UNF_CliPendencia.pas' {FRM_CliPendencia},
  UNF_Turno in 'UNF_Turno.pas' {FRM_Turno},
  UNQ_RGProdutoRC in '..\Retaguarda\UNQ_RGProdutoRC.pas' {QRP_RGProdutoRC: TQuickRep},
  UNQ_RGCortesia in '..\Retaguarda\UNQ_RGCortesia.pas' {QRP_RGCortesia: TQuickRep},
  UNF_ModuloFechaCaixa in 'UNF_ModuloFechaCaixa.pas' {FRM_ModuloFechaCaixa: TDataModule},
  UNF_Observacao in 'UNF_Observacao.pas' {FRM_Observacao},
  UNF_LanMesas in 'UNF_LanMesas.pas' {FRM_LanMesas},
  UNF_MesaLegenda in 'UNF_MesaLegenda.pas' {FRM_MesaLegenda},
  UNF_FinalizaMesa in 'UNF_FinalizaMesa.pas' {FRM_FinalizaMesa},
  UNF_TransDiaria in 'UNF_TransDiaria.pas' {FRM_TransDiaria},
  UNF_Imagem in 'UNF_Imagem.pas' {FRM_Imagem},
  UNF_LanComplemento in 'UNF_LanComplemento.pas' {FRM_LanComplemento},
  UNQ_NotaFiscal in 'UNQ_NotaFiscal.pas' {QRP_NotaFiscal: TQuickRep},
  UNF_NotaFrente in 'UNF_NotaFrente.pas' {FRM_NotaFrente},
  UNF_GeralRelTotais in 'UNF_GeralRelTotais.pas',
  UNF_GeraGerenciais in 'UNF_GeraGerenciais.pas' {FRM_GeraGerenciais},
  UNF_TelQtde in 'UNF_TelQtde.pas' {FRM_TelQtde},
  UNF_DadosECF in 'UNF_DadosECF.pas' {FRM_DadosECF},
  UNF_FilImpCartelas in 'UNF_FilImpCartelas.pas' {FRM_FilImpCartelas},
  UNQ_ImpCartelas in 'UNQ_ImpCartelas.pas' {QRP_ImpCartelas: TQuickRep},
  UNF_Entrega3 in 'UNF_Entrega3.pas' {FRM_EntreBaixa2},
  UNF_Filizola in 'UNF_Filizola.pas' {frm_Filizola},
  UNQ_FichaAberto in 'UNQ_FichaAberto.pas' {QRP_FichaAberto: TQuickRep},
  UNF_AbertaFicha in 'UNF_AbertaFicha.pas' {FRM_AbertaFicha},
  UNF_MiniImpresora in '..\Lib\UNF_MiniImpresora.pas',
  UNF_AgrupaItens in 'UNF_AgrupaItens.pas' {frm_AgrupaItens},
  UNF_DataRegis in 'UNF_DataRegis.pas',
  UNF_FechamentoManualCaixa in 'UNF_FechamentoManualCaixa.pas' {FRM_FechamentoManualCaixa},
  UNF_Sweda in 'UNF_Sweda.pas',
  UNF_Elgin in 'UNF_Elgin.pas',
  UNF_ImpAniver in 'UNF_ImpAniver.pas' {FRM_ImpAniver},
  UNQ_ImpAniver in 'UNQ_ImpAniver.pas' {QRP_ImpAniver: TQuickRep},
  UNF_VariasFormasEntrega in 'UNF_VariasFormasEntrega.pas' {FRM_VariasFormasEntrega},
  UNF_PesPreco in 'UNF_PesPreco.pas' {FRM_PesPreco},
  UNF_MesaStatus in 'UNF_MesaStatus.pas' {FRM_MesaStatus},
  UNQ_MesaStatus in 'UNQ_MesaStatus.pas' {QRP_MesaStatus: TQuickRep},
  UNF_TEFDedicado in 'UNF_TEFDedicado.pas',
  UNF_TEFEdit in 'UNF_TEFEdit.pas' {FRM_TEFEdit},
  UNF_TEFOpcao in 'UNF_TEFOpcao.pas' {FRM_TEFOpcao},
  UNF_EditCheque in 'UNF_EditCheque.pas' {FRM_EditCheque},
  UNF_MensagemL in 'UNF_MensagemL.pas' {FRM_MensagemL},
  UNF_TEFEditC in 'UNF_TEFEditC.pas' {FRM_TEFEditC},
  UNF_MensagemLO in 'UNF_MensagemLO.pas' {FRM_MensagemLO},
  UNF_TEFModulo in 'UNF_TEFModulo.pas' {FRM_TEFModulo: TDataModule},
  UNQ_RGVendas in '..\Retaguarda\UNQ_RGVendas.pas' {QRP_RGVendas: TQuickRep},
  UNF_GarconItem in 'UNF_GarconItem.pas' {FRM_GarconItem},
  UNF_Financeiro in '..\Retaguarda\UNF_Financeiro.pas' {FRM_Financeiro},
  UNQ_RelFinanceiro in '..\Retaguarda\UNQ_RelFinanceiro.pas' {QRP_RelFinanceiro: TQuickRep},
  UNF_FilFinanceiro in '..\Retaguarda\UNF_FilFinanceiro.pas' {FRM_FilFinanceiro},
  UNQ_RelFinanceiroSaldo in '..\Retaguarda\UNQ_RelFinanceiroSaldo.pas' {QRP_RelFinanceiroSaldo: TQuickRep},
  UNF_PagtoFinanceiro in '..\Retaguarda\UNF_PagtoFinanceiro.pas' {FRM_PagtoFinanceiro},
  UNF_PagtoFinanceiroGrupo in '..\Retaguarda\UNF_PagtoFinanceiroGrupo.pas' {FRM_PagtoFinanceiroGrupo},
  UNF_TranfGrupoF in '..\Retaguarda\UNF_TranfGrupoF.pas' {FRM_TranfGrupoF},
  UNF_PagtoConvenio in '..\Retaguarda\UNF_PagtoConvenio.pas' {FRM_PagtoConvenio},
  UNF_Aguardar in '..\Retaguarda\UNF_Aguardar.pas' {FRM_Aguardar},
  UNF_FinanceiroAlteraValor in '..\Retaguarda\UNF_FinanceiroAlteraValor.pas' {FRM_FinanceiroAlteraValor},
  UNF_FinanceiroSenhaAltVal in '..\Retaguarda\UNF_FinanceiroSenhaAltVal.pas' {FRM_FinanceiroSenhaAltVal},
  UNF_Status in '..\Retaguarda\UNF_Status.pas' {FRM_Status},
  UNF_Transf in '..\Retaguarda\UNF_Transf.pas' {FRM_Transf},
  UNF_Extenso in '..\Lib\UNF_Extenso.pas',
  UNQ_RGMensalista1 in '..\Retaguarda\UNQ_RGMensalista1.pas' {QRP_RGMensalista1: TQuickRep},
  UNQ_Entraga in '..\Retaguarda\UNQ_Entraga.pas' {QRP_Entrega: TQuickRep},
  UNQ_ETIQProdutoGond2 in '..\Retaguarda\UNQ_ETIQProdutoGond2.pas' {QRP_ETIQProdutoGond2: TQuickRep},
  UNF_Epson in 'UNF_Epson.pas',
  UNF_InfoEntrega in 'UNF_InfoEntrega.pas' {FRM_InfoEntrega},
  UNF_EntregaEditar in 'UNF_EntregaEditar.pas' {FRM_EntregaEditar},
  UNF_BalcaoMesa in 'UNF_BalcaoMesa.pas' {FRM_BalcaoMesa};

{$R *.res}

begin
   FRM_Entrada := TFRM_Entrada.Create(Application);
   FRM_Entrada.Show;
   FRM_Entrada.Refresh;
   Application.Initialize;
   Application.Title := 'Frente - Caixa';
   Application.HelpFile := 'AJUDA_ARCOIRIS.HLP';
   Application.CreateForm(TFRM_Frente, FRM_Frente);
  Application.CreateForm(TFRM_MensagemDeErro, FRM_MensagemDeErro);
  Application.CreateForm(TFRM_Modulo, FRM_Modulo);
  Application.CreateForm(TFRM_Senha, FRM_Senha);
  Application.CreateForm(TFRM_TEFModulo, FRM_TEFModulo);
  Application.CreateForm(TFRM_TEFOpcao, FRM_TEFOpcao);
  Application.CreateForm(TFRM_TEFEdit, FRM_TEFEdit);
  Application.CreateForm(TFRM_TEFEditC, FRM_TEFEditC);
  Application.CreateForm(TFRM_MensagemL, FRM_MensagemL);
  Application.CreateForm(TFRM_MensagemLO, FRM_MensagemLO);
  Application.CreateForm(TFRM_NewMensagem, FRM_NewMensagem);
  Application.CreateForm(TFRM_EditCheque, FRM_EditCheque);
  Application.CreateForm(TFRM_TelQtde, FRM_TelQtde);
  FRM_Fundo := TFRM_Fundo.Create(Application);
   FRM_Fundo.Show;
   Application.Run;
end.
