unit UNF_Frente;

interface

uses
  SysUtils, Classes, DB, IBTable, SOAPHTTPTrans, IBCustomDataSet, IBQuery,
  ExtCtrls;

type
  TFRM_Frente = class(TDataModule)
    TRM_ATivacao: TTimer;
    IBQ_PesProduto: TIBQuery;
    IBQ_PesProdutoDescLocalImp: TStringField;
    IBQ_PesProdutoCODIGO_ID: TIntegerField;
    IBQ_PesProdutoPRODUTO: TIBStringField;
    IBQ_PesProdutoDESCRICAO: TIBStringField;
    IBQ_PesProdutoPRECO: TFloatField;
    IBQ_PesProdutoPRECOCUSTO: TFloatField;
    IBQ_PesProdutoGRUPO: TIntegerField;
    IBQ_PesProdutoICMS_SN: TIBStringField;
    IBQ_PesProdutoTRIBUTAR: TIntegerField;
    IBQ_PesProdutoBALANCA: TIBStringField;
    IBQ_PesProdutoTARA: TFloatField;
    IBQ_PesProdutoUNIDADE: TIntegerField;
    IBQ_PesProdutoATIVO: TIBStringField;
    IBQ_PesProdutoCOMANDA: TIBStringField;
    IBQ_PesProdutoLOCAL_IMP: TIntegerField;
    IBQ_PesProdutoDESCONTO: TFloatField;
    IBQ_PesProdutoACRESCIMO: TFloatField;
    IBQ_PesProdutoPROD_MTN: TIntegerField;
    IBQ_PesProdutoESTOQUE: TIBStringField;
    IBQ_PesProdutoESTNEGATIVO: TIBStringField;
    IBQ_PesProdutoESTOQUE_FISICO: TFloatField;
    IBQ_PesProdutoESTOQUE_VIRTUAL: TFloatField;
    IBQ_PesProdutoESTOQUEMIN: TFloatField;
    IBQ_PesProdutoESTOQUEMAX: TFloatField;
    IBQ_PesProdutoTEMPO: TIBStringField;
    IBQ_PesProdutoDIA_PROD: TIBStringField;
    IBQ_PesProdutoIMP_PERS: TIBStringField;
    IBQ_PesProdutoVALSALDOENT: TFloatField;
    IBQ_PesProdutoQTDSALDOENT: TFloatField;
    IBQ_PesProdutoTAXA: TFloatField;
    IBQ_PesProdutoTAXA_SN: TIBStringField;
    IBQ_PesProdutoLUCRO: TFloatField;
    IBQ_PesProdutoMOVEL: TIBStringField;
    IBQ_PesProdutoPIS: TFloatField;
    IBQ_PesProdutoREDUCAOICMS: TFloatField;
    IBQ_PesProdutoCOFINS: TFloatField;
    IBQ_PesProdutoICMS: TFloatField;
    IBQ_PesProdutoTRIBUTAR_ANTIGO: TIntegerField;
    IBQ_PesProdutoTRIBUTAR_FORA_ANTIGO: TIntegerField;
    IBQ_PesProdutoPRECO_AGREGADO: TFloatField;
    IBQ_PesProdutoTRIBUTAR_FORA: TIntegerField;
    IBQ_PesProdutoCST: TIntegerField;
    IBQ_PesProdutoCOMISSAO: TFloatField;
    IBQ_PesProdutoCOMISPRSN: TIBStringField;
    IBQ_PesProdutoITEMDATASUL: TIBStringField;
    IBQ_PesProdutoCLASSFISC_DATASUL: TIBStringField;
    IBQ_PesProdutoNATOPERACAO_DATASUL: TIBStringField;
    IBQ_PesProdutoUNITEM_DATASUL: TIBStringField;
    IBQ_PesProdutoUNFAMI_DATASUL: TIBStringField;
    IBQ_PesProdutoCODTRIB_DATASUL: TIBStringField;
    IBQ_PesProdutoPERREDUCAOICMS_DATASUL: TIBStringField;
    IBQ_PesProdutoNIVEL_ISENTO: TIntegerField;
    IBQ_PesProdutoOBSFRENTE: TIBStringField;
    IBQ_PesProdutoNCM: TIBStringField;
    IBQ_PesProdutoBXCARTELA: TIBStringField;
    IBQ_PesProdutoMONTAR: TIBStringField;
    IBQ_PesProdutoTIPO: TIBStringField;
    IBQ_PesProdutoESTLISTA_SN: TIBStringField;
    IBQ_PesProdutoST_ICMSE: TIntegerField;
    IBQ_PesProdutoST_ICMSS: TIntegerField;
    IBQ_PesProdutoST_IPI: TIntegerField;
    IBQ_PesProdutoST_PIS: TIntegerField;
    IBQ_PesProdutoST_COFINS: TIntegerField;
    IBQ_PesProdutoICMSS: TFloatField;
    IBQ_PesProdutoREDS: TFloatField;
    IBQ_PesProdutoIPI: TFloatField;
    IBQ_PesProdutoCODSERVICO: TIBStringField;
    IBQ_PesProdutoISSQN: TFloatField;
    IBQ_PesProdutoCF: TIBStringField;
    IBQ_PesProdutoEXTIPI: TIBStringField;
    IBQ_PesProdutoMODALIDADEBC: TIBStringField;
    HTTPReqResp_CEP: THTTPReqResp;
    IBQ_Obs2: TIBQuery;
    IBQ_Obs2CODIGO_ID: TIntegerField;
    IBQ_Obs2SEQUENCIA: TIntegerField;
    IBQ_Obs2PRODUTO: TIntegerField;
    IBQ_Obs2OBSERVACAO: TMemoField;
    IBQ_Obs: TIBQuery;
    IBQ_ObsSEQUENCIA: TIntegerField;
    IBQ_ObsPRODUTO: TIntegerField;
    IBQ_ObsOBSERVACAO: TMemoField;
    IBQ_PISCOFINS: TIBQuery;
    Timer: TTimer;
    IBQ_Sequencia: TIBQuery;
    IBQ_SequenciaXCOD_ID: TLargeintField;
    IBT_Produtos: TIBTable;
    IBT_ProdutosCODIGO_ID: TIntegerField;
    IBT_ProdutosPRODUTO: TIBStringField;
    IBT_ProdutosDESCRICAO: TIBStringField;
    IBT_ProdutosPRECO: TFloatField;
    IBT_ProdutosPRECOCUSTO: TFloatField;
    IBT_ProdutosGRUPO: TIntegerField;
    IBT_ProdutosICMS_SN: TIBStringField;
    IBT_ProdutosTRIBUTAR: TIntegerField;
    IBT_ProdutosBALANCA: TIBStringField;
    IBT_ProdutosTARA: TFloatField;
    IBT_ProdutosUNIDADE: TIntegerField;
    IBT_ProdutosATIVO: TIBStringField;
    IBT_ProdutosCOMANDA: TIBStringField;
    IBT_ProdutosLOCAL_IMP: TIntegerField;
    IBT_ProdutosDESCONTO: TFloatField;
    IBT_ProdutosACRESCIMO: TFloatField;
    IBT_ProdutosPROD_MTN: TIntegerField;
    IBT_ProdutosESTOQUE: TIBStringField;
    IBT_ProdutosESTNEGATIVO: TIBStringField;
    IBT_ProdutosESTOQUE_FISICO: TFloatField;
    IBT_ProdutosESTOQUE_VIRTUAL: TFloatField;
    IBT_ProdutosESTOQUEMIN: TFloatField;
    IBT_ProdutosESTOQUEMAX: TFloatField;
    IBT_ProdutosTEMPO: TIBStringField;
    IBT_ProdutosDIA_PROD: TIBStringField;
    IBT_ProdutosIMP_PERS: TIBStringField;
    IBT_ProdutosVALSALDOENT: TFloatField;
    IBT_ProdutosQTDSALDOENT: TFloatField;
    IBT_ProdutosTAXA: TFloatField;
    IBT_ProdutosTAXA_SN: TIBStringField;
    IBT_ProdutosLUCRO: TFloatField;
    IBT_ProdutosMOVEL: TIBStringField;
    IBT_ProdutosPIS: TFloatField;
    IBT_ProdutosREDUCAOICMS: TFloatField;
    IBT_ProdutosCOFINS: TFloatField;
    IBT_ProdutosICMS: TFloatField;
    IBT_ProdutosTRIBUTAR_ANTIGO: TIntegerField;
    IBT_ProdutosTRIBUTAR_FORA_ANTIGO: TIntegerField;
    IBT_ProdutosPRECO_AGREGADO: TFloatField;
    IBT_ProdutosTRIBUTAR_FORA: TIntegerField;
    IBT_ProdutosCST: TIntegerField;
    IBT_ProdutosCOMISSAO: TFloatField;
    IBT_ProdutosCOMISPRSN: TIBStringField;
    IBT_ProdutosITEMDATASUL: TIBStringField;
    IBT_ProdutosCLASSFISC_DATASUL: TIBStringField;
    IBT_ProdutosNATOPERACAO_DATASUL: TIBStringField;
    IBT_ProdutosUNITEM_DATASUL: TIBStringField;
    IBT_ProdutosUNFAMI_DATASUL: TIBStringField;
    IBT_ProdutosCODTRIB_DATASUL: TIBStringField;
    IBT_ProdutosPERREDUCAOICMS_DATASUL: TIBStringField;
    IBT_ProdutosNIVEL_ISENTO: TIntegerField;
    IBT_ProdutosOBSFRENTE: TIBStringField;
    IBQ_PesMesaItem: TIBQuery;
    IBQ_PesMesaItemCODIGO_ID: TIntegerField;
    IBQ_PesMesaItemMESA: TIntegerField;
    IBQ_PesMesaItemSEQUENCIA: TIntegerField;
    IBQ_PesMesaItemGARCOM: TIntegerField;
    IBQ_PesMesaItemPRODUTO: TIntegerField;
    IBQ_PesMesaItemQUANTIDADE: TFloatField;
    IBQ_PesMesaItemCANCELADA: TIBStringField;
    IBQ_PesMesaItemIMP_REMOTA: TIBStringField;
    IBQ_PesMesaItemPONTOVENDA: TIntegerField;
    IBQ_PesMesaItemHORA: TIBStringField;
    IBQ_PesMesaItemDATE: TDateField;
    IBQ_PesMesaItemMESAFECHA: TIntegerField;
    IBQ_PesMesaItemSEQFECHA: TIntegerField;
    IBQ_PesMesaItemGRUPO: TIntegerField;
    IBQ_PesMesaItemPRC_UNITARIO: TFloatField;
    IBQ_PesMesaItemBALANCA: TIBStringField;
    IBQ_PesMesaItemHO: TIBStringField;
    IBQ_PesMesaItemTEMPO: TDateTimeField;
    IBQ_PesMesaItemOPCANCEL: TIntegerField;
    IBQ_PesMesaItemALIQUOTA: TIntegerField;
    IBQ_PesMesaItemDATA_INICIO: TDateField;
    IBQ_PesMesaItemDATA_FINAL: TDateField;
    IBQ_PesMesaItemHORA_INICIO: TIBStringField;
    IBQ_PesMesaItemHORA_FINAL: TIBStringField;
    IBQ_PesMesaItemTEMPO_INICIAL: TDateTimeField;
    IBQ_PesMesaItemTEMPO_FINAL: TDateTimeField;
    IBQ_PesMesaItemDESCONTO: TFloatField;
    IBQ_PesMesaItemFINALIZADA: TIBStringField;
    IBQ_PesMesaItemOBS: TIBStringField;
    IBQ_PesMesaItemIMP_DIARIA: TIBStringField;
    IBQ_PesMesaItemIMP_CONTINT: TIBStringField;
    IBQ_PesMesaItemIMP_CANCELINT: TIBStringField;
    IBQ_PesMesaItemCLIENTEDIARIA: TIntegerField;
    IBQ_PesMesaItemACRESCIMO: TFloatField;
    IBQ_PesMesaItemTAXA: TFloatField;
    IBQ_PesMesaItemVAL_DESCONTO: TFloatField;
    IBQ_PesMesaItemVAL_ACRESCIMO: TFloatField;
    IBQ_PesMesaItemVAL_TAXA: TFloatField;
    IBQ_PesMesaItemVAL_PRODUTO: TFloatField;
    IBQ_PesMesaItemOBSERVACAO: TMemoField;
    IBQ_PesCancela: TIBQuery;
    IBQ_PesCancelaCODIGO_ID: TIntegerField;
    IBQ_PesCancelaMESA: TIntegerField;
    IBQ_PesCancelaSEQUENCIA: TIntegerField;
    IBQ_PesCancelaGARCOM: TIntegerField;
    IBQ_PesCancelaPRODUTO: TIntegerField;
    IBQ_PesCancelaQUANTIDADE: TFloatField;
    IBQ_PesCancelaCANCELADA: TIBStringField;
    IBQ_PesCancelaIMP_REMOTA: TIBStringField;
    IBQ_PesCancelaPONTOVENDA: TIntegerField;
    IBQ_PesCancelaHORA: TIBStringField;
    IBQ_PesCancelaDATE: TDateField;
    IBQ_PesCancelaMESAFECHA: TIntegerField;
    IBQ_PesCancelaSEQFECHA: TIntegerField;
    IBQ_PesCancelaGRUPO: TIntegerField;
    IBQ_PesCancelaPRC_UNITARIO: TFloatField;
    IBQ_PesCancelaBALANCA: TIBStringField;
    IBQ_PesCancelaHO: TIBStringField;
    IBQ_PesCancelaTEMPO: TDateTimeField;
    IBQ_PesCancelaOPCANCEL: TIntegerField;
    IBQ_PesCancelaALIQUOTA: TIntegerField;
    IBQ_PesCancelaDATA_INICIO: TDateField;
    IBQ_PesCancelaDATA_FINAL: TDateField;
    IBQ_PesCancelaHORA_INICIO: TIBStringField;
    IBQ_PesCancelaHORA_FINAL: TIBStringField;
    IBQ_PesCancelaTEMPO_INICIAL: TDateTimeField;
    IBQ_PesCancelaTEMPO_FINAL: TDateTimeField;
    IBQ_PesCancelaDESCONTO: TFloatField;
    IBQ_PesCancelaFINALIZADA: TIBStringField;
    IBQ_PesCancelaOBS: TIBStringField;
    IBQ_PesCancelaIMP_DIARIA: TIBStringField;
    IBQ_PesCancelaIMP_CONTINT: TIBStringField;
    IBQ_PesCancelaIMP_CANCELINT: TIBStringField;
    IBQ_PesCancelaCLIENTEDIARIA: TIntegerField;
    IBQ_PesCancelaACRESCIMO: TFloatField;
    IBQ_PesCancelaTAXA: TFloatField;
    IBQ_PesCancelaVAL_DESCONTO: TFloatField;
    IBQ_PesCancelaVAL_ACRESCIMO: TFloatField;
    IBQ_PesCancelaVAL_TAXA: TFloatField;
    IBQ_PesCancelaVAL_PRODUTO: TFloatField;
    IBQ_CondPagtoDesAcre: TIBQuery;
    IBQ_Pagamento: TIBQuery;
    DTQ_Pesquisa: TDataSource;
    IBQ_Pesquisa: TIBQuery;
    IBQ_Grava: TIBQuery;
    IBQ_TKTSequencia: TIBQuery;
    IBQ_TKTSequenciaXCOD_ID: TLargeintField;
    IBQ_VerFichaFinaliz: TIBQuery;
    IBQ_VerFichaFinalizFINALIZADO: TDateTimeField;
    IBQ_VerFichaFinalizCONTADOR: TIntegerField;
    IBQ_AbreFichaFinaliz: TIBQuery;
    IBQ_AbreFichaFinalizCODIGO_ID: TIntegerField;
    IBQ_AbreFichaFinalizFICHA: TIntegerField;
    IBQ_AbreFichaFinalizSEQUENCIA: TIntegerField;
    IBQ_AbreFichaFinalizSTATUS: TIBStringField;
    IBQ_AbreFichaFinalizATIVO: TIBStringField;
    IBQ_AbreFichaFinalizCONSULTA: TIBStringField;
    IBQ_AbreFichaFinalizTRAVA: TIBStringField;
    IBQ_AbreFichaFinalizDIGITO: TSmallintField;
    IBQ_AbreFichaFinalizTP_FICHA: TIBStringField;
    IBQ_AbreFichaFinalizOPERADOR: TIntegerField;
    IBQ_AbreFichaFinalizPRODUCAO: TIBStringField;
    IBQ_AbreFichaFinalizQUARTO: TIBStringField;
    IBQ_VerERROFichas: TIBQuery;
    IBQ_PesqPeriodo: TIBQuery;
    IBQ_PesqPeriodoOPERADOR: TIBStringField;
    IBQ_PesqPeriodoTURNO: TIBStringField;
    IBQ_CUITEM: TIBQuery;
    IBQ_CUITEMCODIGO_ID: TIntegerField;
    IBQ_CUITEMMESA: TIntegerField;
    IBQ_CUITEMSEQUENCIA: TIntegerField;
    IBQ_CUITEMGARCOM: TIntegerField;
    IBQ_CUITEMPRODUTO: TIntegerField;
    IBQ_CUITEMQUANTIDADE: TFloatField;
    IBQ_CUITEMCANCELADA: TIBStringField;
    IBQ_CUITEMIMP_REMOTA: TIBStringField;
    IBQ_CUITEMPONTOVENDA: TIntegerField;
    IBQ_CUITEMHORA: TIBStringField;
    IBQ_CUITEMDATE: TDateField;
    IBQ_CUITEMMESAFECHA: TIntegerField;
    IBQ_CUITEMSEQFECHA: TIntegerField;
    IBQ_CUITEMGRUPO: TIntegerField;
    IBQ_CUITEMPRC_UNITARIO: TFloatField;
    IBQ_CUITEMBALANCA: TIBStringField;
    IBQ_CUITEMHO: TIBStringField;
    IBQ_CUITEMTEMPO: TDateTimeField;
    IBQ_CUITEMOPCANCEL: TIntegerField;
    IBQ_CUITEMALIQUOTA: TIntegerField;
    IBQ_CUITEMDATA_INICIO: TDateField;
    IBQ_CUITEMDATA_FINAL: TDateField;
    IBQ_CUITEMHORA_INICIO: TIBStringField;
    IBQ_CUITEMHORA_FINAL: TIBStringField;
    IBQ_CUITEMTEMPO_INICIAL: TDateTimeField;
    IBQ_CUITEMTEMPO_FINAL: TDateTimeField;
    IBQ_CUITEMDESCONTO: TFloatField;
    IBQ_CUITEMFINALIZADA: TIBStringField;
    IBQ_CUITEMOBS: TIBStringField;
    IBQ_CUITEMIMP_DIARIA: TIBStringField;
    IBQ_CUITEMIMP_CONTINT: TIBStringField;
    IBQ_CUITEMIMP_CANCELINT: TIBStringField;
    IBQ_CUITEMCLIENTEDIARIA: TIntegerField;
    IBQ_CUITEMACRESCIMO: TFloatField;
    IBQ_CUITEMTAXA: TFloatField;
    IBQ_CUITEMVAL_TAXA: TFloatField;
    IBQ_CUITEMVAL_DESCONTO: TFloatField;
    IBQ_CUITEMVAL_ACRESCIMO: TFloatField;
    IBQ_CUITEMVAL_PRODUTO: TFloatField;
    IBQ_CUITEMALIQUO: TIBStringField;
    IBQ_CUITEMPIS: TFloatField;
    IBQ_CUITEMCOFINS: TFloatField;
    IBQ_CUITEMICMS: TFloatField;
    IBQ_CUITEMCOMISSAOPR: TFloatField;
    IBQ_CUITEMCOMISSAOFU: TFloatField;
    IBQ_CUITEMCOMISPRSN: TIBStringField;
    IBQ_CUITEMCORTESIA: TIBStringField;
    IBQ_CUITEMTURNO: TIntegerField;
    IBQ_CUITEMSTATUSCONT: TIBStringField;
    IBQ_CUITEMREDUCAO: TFloatField;
    IBQ_CUITEMOBSERVACAO: TMemoField;
    IBQ_CUITEMCOMPLEMENTO: TIBStringField;
    IBQ_CUITEMPOSICAO: TIBStringField;
    IBQ_CUITEMLIGACOMP: TIntegerField;
    IBQ_CUITEMNIVEL_ISENTO: TIntegerField;
    IBQ_CUITEMIMPRESSO: TIBStringField;
    IBQ_CUITEMPESSOAS: TIntegerField;
    IBQ_CUITEMCODIGO_ID1: TIntegerField;
    IBQ_CUITEMMESA1: TIntegerField;
    IBQ_CUITEMSEQUENCIA1: TIntegerField;
    IBQ_CUITEMVALOR: TFloatField;
    IBQ_CUITEMTROCO: TFloatField;
    IBQ_CUITEMTIPO_PAGTO: TIntegerField;
    IBQ_CUITEMHORA_PAGTO: TIBStringField;
    IBQ_CUITEMDATA_PAGTO: TDateField;
    IBQ_CUITEMOPERADOR: TIntegerField;
    IBQ_CUITEMDESCONTO1: TFloatField;
    IBQ_CUITEMCANCELADO: TIBStringField;
    IBQ_CUITEMPONTOVENDA1: TIntegerField;
    IBQ_CUITEMSEQ_FISCAL: TIBStringField;
    IBQ_CUITEMNUM_CAIXA: TIBStringField;
    IBQ_CUITEMCOK: TIBStringField;
    IBQ_CUITEMMESAFECHA1: TIntegerField;
    IBQ_CUITEMSEQFECHA1: TIntegerField;
    IBQ_CUITEMTEMPO1: TDateTimeField;
    IBQ_CUITEMOPCANCEL1: TIntegerField;
    IBQ_CUITEMCLIENTE: TIntegerField;
    IBQ_CUITEMVAL_DESCONTOI: TFloatField;
    IBQ_CUITEMVAL_ACRESCIMOI: TFloatField;
    IBQ_CUITEMVAL_TAXAI: TFloatField;
    IBQ_CUITEMCAT_CNPJ: TIBStringField;
    IBQ_CUITEMCAT_NOME: TIBStringField;
    IBQ_CUITEMCAT_ENDERECO: TIBStringField;
    IBQ_CUITEMNUMSERIEIMPRESSORA: TIBStringField;
    IBQ_CUITEMCORTESIA1: TIBStringField;
    IBQ_CUITEMTURNO1: TIntegerField;
    IBQ_CUITEMIMPRESSO1: TIBStringField;
    IBQ_CUITEMPESSOAS1: TIntegerField;
    IBQ_CUITEMDescProduto: TStringField;
    procedure Commit_Work_;
    procedure Rollback;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FRM_Frente: TFRM_Frente;

implementation

uses UNF_Modulo;

{$R *.dfm}

procedure TFRM_Frente.Commit_Work_;
begin
   FRM_Modulo.IBTransaction_Commit.Active := true;
   FRM_Modulo.IBTransaction_Commit.Commit;

   FRM_Modulo.IBTransaction1.CommitRetaining;
   FRM_Modulo.IBTransactionF.CommitRetaining;
   FRM_Modulo.IBTransactionO.CommitRetaining;
end;

procedure TFRM_Frente.Rollback;
begin
   FRM_Modulo.IBTransaction_Commit.Active := true;
   FRM_Modulo.IBTransaction_Commit.Rollback;

   FRM_Modulo.IBTransaction1.RollbackRetaining;
   FRM_Modulo.IBTransactionF.RollbackRetaining;
   FRM_Modulo.IBTransactionO.RollbackRetaining;
end;

end.
