unit UNF_FilFechaCaixa1Novo;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls;

type
  TFRM_FilFechaCaixa1Novo = class(TForm)
    Label1: TLabel;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FRM_FilFechaCaixa1Novo: TFRM_FilFechaCaixa1Novo;

implementation

{$R *.dfm}

end.
